# Generated by Django 6.0.6 on 2026-06-05 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='finance.dailyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('food', 'Food'), ('groceries', 'Groceries'), ('clothing', 'Clothing'), ('custom', 'Custom')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.dailyrecord')),
            ],
        ),
    ]
